version: "3.7"

services:
  es:
    container_name: news_es_test
    image: elasticsearch:7.0.1
    ports:
      - "9207:9200"
      - "9307:9300"
    environment:
      discovery.type: single-node
  rabbitmq:
    container_name: news_rabbitmq_test
    image: rabbitmq:3-management
    ports:
      - "5677:5672"
      - "15677:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
  mysql:
    container_name: news_mysql_test
    image: circleci/mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
    entrypoint:
      sh -c "echo 'CREATE DATABASE IF NOT EXISTS news; CREATE DATABASE IF NOT EXISTS news;' > /docker-entrypoint-initdb.d/init.sql;
      /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "
