// Code generated by MockGen. DO NOT EDIT.
// Source: module/v1/repository/repository_contract.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/yaya-ri/API-news/module/v1/model"
)

// MockNewsRepositoryInterface is a mock of NewsRepositoryInterface interface
type MockNewsRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockNewsRepositoryInterfaceMockRecorder
}

// MockNewsRepositoryInterfaceMockRecorder is the mock recorder for MockNewsRepositoryInterface
type MockNewsRepositoryInterfaceMockRecorder struct {
	mock *MockNewsRepositoryInterface
}

// NewMockNewsRepositoryInterface creates a new mock instance
func NewMockNewsRepositoryInterface(ctrl *gomock.Controller) *MockNewsRepositoryInterface {
	mock := &MockNewsRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockNewsRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockNewsRepositoryInterface) EXPECT() *MockNewsRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Store mocks base method
func (m *MockNewsRepositoryInterface) Store(model *models.News) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", model)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store
func (mr *MockNewsRepositoryInterfaceMockRecorder) Store(model interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockNewsRepositoryInterface)(nil).Store), model)
}

// Find mocks base method
func (m *MockNewsRepositoryInterface) Find(id uint) (models.News, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", id)
	ret0, _ := ret[0].(models.News)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find
func (mr *MockNewsRepositoryInterfaceMockRecorder) Find(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockNewsRepositoryInterface)(nil).Find), id)
}
